Use resource file instead.

diff --git a/src/saltminionskeys b/src/saltminionskeys
--- a/src/saltminionskeys
+++ b/src/saltminionskeys
@@ -8,17 +8,12 @@
 #############################################################
 
 SVER=0.0.1
-RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
 
-[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
+for RCFILE in $(ls /usr/lib/supportconfig/resources/*.rc); do
+    [ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }
+done
 
 section_header "Supportconfig Plugin for SaltStack, v${SVER}"
 
-if ! rpm -q salt &>/dev/null; then
-  echo "ERROR: Salt package(s) not installed"
-  echo
-  exit 111
-fi
-
-# Keys of the minions
+check_packages "salt" "salt-master"
 plugin_command "salt-key -L"
